### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aszepieniec** [Neptune-Crypto/neptune-core#10]
- [x] Peer-to-peer Networking
   - [x] peer discovery
   - [ ] peer authentication
   - [ ] end-to-end encryption
   - [ ] onion routing
 - [x] Daemon Application Architecture
   - [x] main thread
   - [x] peer thread
   - [x] mine thread
   - [x] RPC thread
   - [x] RPC interface
   - [x] windows & mac support
   - [x] binaries
 - [x] Synchronization
   - [x] archival block synchronization
   - [x] UTXO synchronization from blocks
 - [x] Blockchain Logic
   - [x] Transaction
     - [x] kernel definition and MAST hash
     - [x] validity program
       - [x] kernel to outputs
       - [x] removal records integrity
       - [x] collect lock scripts
       - [x] collect type scripts
     - [x] single proof
     - [x] merging
       - [x] with recursion
     - [x] updating
     - [ ] integral mempool
   - [x] UTXO
     - [x] privacy: mutator sets
     - [x] lockable UTXOs
     - [ ] lock-free UTXOs
     - [x] currency logic
     - [x] arbitrary state evolution
   - [x] addresses
     - [x] generation
     - [x] change (untraced)
     - [x] change (traced)
     - [x] online
     - [x] encoding
       - [x] bech32m
       - [ ] bech32m error location
       - [ ] alternative
   - [x] Block
     - [x] parameter adjustment (spec)
     - [x] parameter adjustment (logic)
     - [x] validity program
       - [x] transaction validity (rust / tasm)
       - [ ] parameter update (rust / tasm)
       - [ ] previous block validity (rust / tasm)
     - [x] single proof
 - [x] Wallet
   - [x] generate tool  
   - [x] seed phrase
   - [x] addresses
     - [x] generation
     - [x] change (untraced)
     - [x] change (traced)
     - [x] online
     - [x] encoding
       - [x] bech32m
       - [ ] bech32m error location
       - [ ] alternative
 - [x] Documentation
 - [x] User Interface
   - [x] console
   - [x] command-line
     - [x] overview
     - [x] peers
     - [x] transaction history
     - [x] send
     - [x] receive
     - [x] blocks  
   - [ ] graphical

**Comment by Sword-Smith** [comment]
Closing in favor of new issue, as we decided to launch without succinctness and soft-fork that in later.. Please open a new one to track requirements if so desired.
